#+TITLE: ECE 4760 Laser Projector Progress Report Week 2
#+AUTHOR: Peter Friend (pcf38), Istvan Burbank (ipb7), James Cassell (jcc384)
#+OPTIONS: toc:nil

This week we worked on fleshing out the circuit designs, finalizing the pinout on the MCU, experimenting with new multi-color lasers and building the mirror carousel.

* Istvan
I received the mirror carousel from the 3D printing shop this week and have begun affixing the mirrors.
I also have been designing a current-source to supply the lasers with which will use a NPN transistor and three resistors to provide a fixed current across laser diode, even as the impedence of the diode changes.

Lastly, I have designed the functional description of how the projector will work at high detail which I will transcribe into code this week. Find a summary below:

The projector consists of a spinning x-scan mirror that scans left to right, and
a y-scan mirror that scans from top to bottom. At the start of each row the
`row_trigger` exhibits a rising edge. After that edge, pixels are clocked out by
DMA triggered by the `pixel_clock`. After all of the pixels have been clocked
out, the DMA interrupts the CPU which moves the y-stage to the next scan line
(allowing it to settle before pixels are clocked out for the next row) and the
DMA is configured the next row.


* Peter

* James

This week I worked on calculating what RPM our mirrors/fan needs to be spinning at in order to get a desired resolution.
The main focus of the week though included getting the lasers working.
I recieved several laser pens in the mail from ebay, and disassembled one of them for testing with.
The pen was torn apart so to get to the PCB with the laser diode attached.
After seeing that there is a voltage control circuit on the PCB, it was determined that it needs to be removed so we can have varying intensity.
The laser diode was desoldered and then time was spent looking online for documentation on the part to we can know what each of the leads on it does along with how we should power the device.
In the case that we can't find documentation, I met with Prof. Pollock to talk about what I should probably expect and methods to find out what each of the leads are based on experiments.
