#+TITLE: ECE 4760 Laser Projector Progress Report Week 3
#+AUTHOR: Peter Friend (pcf38), Istvan Burbank (ipb7), James Cassell (jcc384)
#+OPTIONS: toc:nil ^:{}

This week we worked more on the software and the laser circuits.

* Istvan
I worked on adding automatically-generating documentation to the code which we will be able to export to HTML and include in our project page.
Additionally, I helped James a little with the laser control circuits.
Lastly, I started the physical assembly of the device.

* Peter
I worked on boilerplate and figure numbering and referencing for the webpage.
I also worked on implementing a moving cursor using the joystick module previously written.
Following this cursor module I began work on simple button drawing GUI functions.
I also began several refactors to improve software architecture, notably moving a crucial color data structure.

* James
After finishing up the circuit for the variable intensity control of the red laser. I worked on testing what each of the leads did on both the green and the blue lasers, since they have three leads instead of two. For the green laser, after finding which leads I can use to control intensity, I designed, built, and tested a circuit which allows us to have variable intensity control of the green laser. I then worked on the blue laser and discovering what its leads do. After figuring out which leads to hook up a power and ground to, I experimentally found values for current and different intensities. Lastly, I used those intensities to design a circuit so that the PIC32 can digitaly control the blue laser intensity.
